name = "koriyama-open-data-hub"
main = "src/index.ts"
compatibility_date = "2026-05-25"

[observability]
enabled = true

[triggers]
crons = [
  "0 * * * *"
]

[[d1_databases]]
binding = "DB"
database_name = "koriyama-open-data-hub-prod"
database_id = "cb6e3e65-f79c-469c-906e-875f36ffe911"
