name = "civic-koriyama-data"
main = "src/index.ts"
compatibility_date = "2026-05-25"
workers_dev = false

[[routes]]
pattern = "civic-koriyama-data.alflag.org"
custom_domain = true

[assets]
directory = "./public"

[observability]
enabled = true

[[ratelimits]]
name = "API_RATE_LIMITER"
namespace_id = "2026061701"

  [ratelimits.simple]
  limit = 30
  period = 60

[triggers]
crons = [
  "0 * * * *"
]

[[d1_databases]]
binding = "DB"
database_name = "civic-koriyama-data-prod"
database_id = "cb6e3e65-f79c-469c-906e-875f36ffe911"
